tasks:
# Переконфигурируем GRUB
  - name: Configuring GRUB /
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg

# Обновим образ initrd
  - name: Change image initrd
    shell: cd /boot ; for i in `ls initramfs-*img`; do dracut -v $i `echo $i|sed "s/initramfs-//g; s/.img//g"` --force; done

# Меняем раздел в grub.cfg
  - name: Change grub.cfg
    shell: sed -i 's/rd.lvm.lv=VolGroup00\/LogVol00/rd.lvm.lv=vg_root\/lv_root/g' /boot/grub2/grub.cfg


# # Перезагружаем машину
#   - name: Reboot
#     reboot: